# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e31d5b362e299fb4b94828ebf09da00260bbba6d3dd44cc32c8676f5910046fe8847c908924fb50bbe5a0d061b445f0cc7d8134d98f74504722826ad4caaee5

test:
  secret_key_base: fbf4963296ab4dab2f02e10b6a5cdcfef7ee463bac98b7deb8de9ca5d9627f7ea59ad3824a8bbcd95708a44865685a466bc22cefcd8d223984b523a5316b234a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
